const root=document.getElementById('root');
const assets=['Gas turbine','Steam turbine','Bearing','Pump','Truck tire','Aircraft engine'];
const factors=[['criticality','Asset criticality'],['data','Sensor-data availability'],['history','Historical failure data'],['physics','Physics-model availability'],['safety','Safety impact'],['interpretability','Interpretability requirement'],['compute','Compute budget'],['rul','RUL requirement']];
const strategies=[
 ['Heuristic / threshold','Threshold','#8295a2',[.25,.10,.04,.12,.16,.17,.13,.03],'Fast, transparent alerts','Weak long-horizon prediction','Low','High','Stable, well-understood failure modes',[92,24]],
 ['Statistical','Statistical','#3678a5',[.16,.22,.20,.07,.11,.11,.09,.04],'Reliable trend and uncertainty','Limited nonlinear behavior','Medium','High','Repeatable degradation patterns',[74,53]],
 ['Physics-based','Physics-based','#009a9f',[.13,.10,.04,.20,.18,.18,.07,.10],'Causal and explainable','Costly model calibration','Low–medium','High','Safety-critical engineered assets',[88,72]],
 ['AI / ML','AI / ML','#6557b7',[.07,.27,.25,.02,.08,.03,.14,.14],'Learns complex signatures','Opaque outside training range','High','Medium','Sensor-rich fleets',[37,89]],
 ['Hybrid physics + AI','Hybrid','#e77425',[.09,.14,.08,.18,.16,.14,.06,.15],'High prediction with constraints','Highest integration complexity','Medium–high','Emerging','Critical assets needing RUL',[65,96]]
];
let state={page:'selector',asset:'Gas turbine',criticality:88,data:78,history:64,physics:84,safety:91,interpretability:82,compute:58,rul:100};
const rank=()=>strategies.map(s=>{const cs=factors.map((f,i)=>({label:f[1],value:Math.round(state[f[0]]*s[3][i])}));return{s,cs,score:cs.reduce((a,b)=>a+b.value,0)}}).sort((a,b)=>b.score-a.score);
function header(){return `<header class="topbar"><div class="topbar-inner"><button class="brand" data-page="selector"><span class="brand-mark"><span></span></span><span><strong>PrognosIQ</strong><small>Predictive Maintenance Strategy Advisor</small></span></button><nav><button data-page="selector" class="${state.page==='selector'?'active':''}">Strategy selector</button><button data-page="case" class="${state.page==='case'?'active':''}">Degradation case study</button></nav><span class="synthetic-status"><i></i>Synthetic research model</span></div></header>`}
function range(k,l,v=state[k]){return `<div class="range-control"><div><label>${l}</label><output>${v}%</output></div><input data-key="${k}" aria-label="${l}" type="range" min="0" max="100" value="${v}"></div>`}
function selector(){const r=rank(),w=r[0];return `<main class="page shell"><div class="page-heading"><div><p class="eyebrow">01 / Strategy selector</p><h1>Find the right prognostics approach</h1><p>Tune asset conditions to compare five strategies with a transparent, deterministic scoring model.</p></div><span class="method-pill">✓ Methodology mode · no model training</span></div><div class="selector-layout">
<aside class="card controls-card"><div class="card-heading"><span class="icon-box">▦</span><div><h2>Asset profile</h2><p>Set decision conditions</p></div></div><label class="field-label">Asset type</label><select id="asset">${assets.map(a=>`<option ${a===state.asset?'selected':''}>${a}</option>`).join('')}</select>${factors.slice(0,7).map(f=>range(f[0],f[1])).join('')}<div class="switch-row"><div><strong>RUL prediction</strong><small>Remaining-useful-life output required</small></div><button id="rul" class="switch ${state.rul>50?'on':''}"><span></span></button></div></aside>
<section class="selector-results"><div class="card recommendation"><div class="rec-copy"><span class="rec-label">Recommended strategy</span><p>Best fit for ${state.asset.toLowerCase()}</p><h2>${w.s[0]}</h2><div class="score-big">${w.score}<small>/ 100 suitability</small></div><p class="rec-summary">Balances forecast capability, engineering constraints and decision transparency for the selected operating context.</p><button class="light-button" data-page="case">Open degradation case study <span>↗</span></button></div><div class="contribution-panel"><p class="mini-title">Why this recommendation</p>${w.cs.sort((a,b)=>b.value-a.value).slice(0,5).map(c=>`<div class="contribution"><span>${c.label}</span><div><i style="width:${Math.min(100,c.value*4)}%"></i></div><strong>+${c.value}</strong></div>`).join('')}<small>Contributions are rounded weighted points. Total score is deterministic.</small></div></div>
<div class="card ranking-card"><div class="section-head"><div><p class="eyebrow">Weighted suitability</p><h2>Strategy scores</h2></div><span>0—100 index</span></div>${r.map((x,i)=>`<div class="rank-row"><span class="rank-number ${i?'':'first'}">${String(i+1).padStart(2,'0')}</span><div class="rank-name"><strong>${x.s[0]}</strong><small>${i?'Alternative approach':'Recommended fit'}</small></div><div class="bar"><i style="width:${x.score}%;background:${x.s[2]}"></i></div><b>${x.score}</b></div>`).join('')}</div>
<div class="split-row"><div class="card strategy-map"><div class="section-head"><div><p class="eyebrow">Strategy map</p><h2>Interpretability vs prediction capability</h2></div></div><div class="map-area"><span class="axis-y">Prediction capability</span><span class="axis-x">Interpretability</span>${strategies.map(s=>`<div class="map-dot" style="left:${s[9][0]}%;bottom:${s[9][1]}%;background:${s[2]}"><span>${s[1]}</span></div>`).join('')}</div></div><div class="card logic-card"><p class="eyebrow">Model logic</p><h2>How scoring works</h2><p>Each input is normalized from 0–100 and multiplied by a strategy-specific weight. The highest total is recommended.</p><div class="formula"><span>Σ</span><code>input × strategy weight</code></div><p class="note">Synthetic decision model—not an asset diagnostic.</p></div></div>
<div class="approaches"><div class="section-head"><div><p class="eyebrow">Approach library</p><h2>Strengths, limits and readiness</h2></div></div><div class="approach-grid">${strategies.map(s=>`<article class="approach-card" style="border-top-color:${s[2]}"><div><h3>${s[0]}</h3><span>${s[7]} maturity</span></div><dl><dt>Strength</dt><dd>${s[4]}</dd><dt>Limitation</dt><dd>${s[5]}</dd><dt>Data requirement</dt><dd>${s[6]}</dd><dt>Applicability</dt><dd>${s[8]}</dd></dl></article>`).join('')}</div></div></section></div></main>`}
function chart(){let p=[];for(let i=0;i<=40;i++){let x=i*2.5,y=i<24?98-i*.72+Math.sin(i*.7)*1.5:81-(i-24)*2.92+Math.sin(i*.6);p.push([44+x*8.7,24+(100-Math.max(24,y))*2.25])}const poly=a=>a.map(q=>q.join(',')).join(' ');return `<svg class="health-chart" viewBox="0 0 960 300"><defs><linearGradient id="f" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#e77425" stop-opacity=".22"/><stop offset="1" stop-color="#e77425" stop-opacity="0"/></linearGradient></defs>${[0,25,50,75,100].map(v=>`<line x1="44" x2="914" y1="${249-v*2.25}" y2="${249-v*2.25}" stroke="#e5ecef"/><text x="8" y="${253-v*2.25}" font-size="11" fill="#788b96">${v}%</text>`).join('')}<rect x="566" y="24" width="348" height="225" fill="#f8fafb"/><line x1="566" x2="566" y1="24" y2="249" stroke="#1d8c92" stroke-dasharray="4 4"/><line x1="44" x2="914" y1="170" y2="170" stroke="#ca4b4d" stroke-width="2" stroke-dasharray="6 5"/><text x="785" y="163" fill="#b63e42" font-size="11">FAILURE THRESHOLD · 35%</text><polyline points="${poly(p.slice(0,24))}" fill="none" stroke="#397aa2" stroke-width="3"/><polyline points="${poly(p.slice(23,29))}" fill="none" stroke="#009a9f" stroke-width="4"/><polyline points="${poly(p.slice(28))}" fill="none" stroke="#e77425" stroke-width="3" stroke-dasharray="7 6"/><circle cx="653" cy="${p[28][1]}" r="6" fill="#fff" stroke="#009a9f" stroke-width="3"/><text x="42" y="285" font-size="11" fill="#788b96">−120 days</text><text x="548" y="285" font-size="11" fill="#087b81">TODAY</text><text x="870" y="285" font-size="11" fill="#788b96">+90 days</text></svg>`}
const matrix=[['Threshold','Low','Low','Very high','Low','High','Low'],['Statistical','Medium','Medium','High','Medium','High','Low–medium'],['Physics-based','High','Low–medium','Very high','High','High','Medium'],['AI / ML','High','Very high','Low','High','Medium','High'],['Hybrid','Very high','High','High','Very high','Emerging','High']];
function badge(v){return ['Very high','High'].includes(v)?'badge high':['Low','Low–medium'].includes(v)?'badge low':'badge medium'}
function casePage(){const r=rank(),w=r[0],signals=[['Temperature','574 °C','+18.4'],['Vibration','5.8 mm/s','+1.2'],['Pressure','16.9 bar','−0.8'],['Load','86 %','+3.1'],['Efficiency','89.4 %','−2.6'],['Operating hours','6,420 h','+480']];return `<main class="page shell"><div class="page-heading"><div><p class="eyebrow">02 / Degradation case study</p><h1>Synthetic gas turbine degradation outlook</h1><p>A lightweight condition-health scenario showing history, current deterioration and a constrained forecast.</p></div><button class="outline-button" data-page="selector">← Back to strategy selector</button></div><div class="case-banner"><strong>100% synthetic industrial data</strong><span>Illustrative signals only · not calibrated to any real asset or fleet</span></div>
<section class="metric-grid">${[['Current health','63','%','teal'],['Degradation rate','0.42','% / day',''],['Estimated RUL','74','days','orange'],['Confidence','82','%',''],['Maintenance window','28–46','days','dark']].map(m=>`<article class="metric ${m[3]}"><p>${m[0]} <em>SYNTHETIC</em></p><div><strong>${m[1]}</strong><span>${m[2]}</span></div><small>synthetic estimate</small></article>`).join('')}</section>
<section class="card chart-card"><div class="section-head"><div><p class="eyebrow">Condition health index · synthetic</p><h2>Historical health and degradation forecast</h2></div><div class="legend"><span class="hist">Historical</span><span class="curr">Current</span><span class="forecast">Forecast</span><span class="threshold">Failure threshold</span></div></div>${chart()}<div class="chart-callout"><span>Today · 6,420 h</span><strong>Forecast crosses threshold near day 74</strong><span>90% synthetic interval: 61–92 days</span></div></section>
<section class="signal-grid">${signals.map(s=>`<article class="card signal-card"><div><p>${s[0]} <em>SYNTHETIC</em></p><strong>${s[1]}</strong><span class="${s[2][0]==='−'?'down':'up'}">${s[2]} / 30d</span><svg viewBox="0 0 100 42"><polyline points="2,36 18,31 34,34 50,24 66,26 82,13 98,8" fill="none" stroke="#16878b" stroke-width="3"/></svg></div></article>`).join('')}</section>
<section class="case-split"><div class="card matrix-card"><div class="section-head"><div><p class="eyebrow">Method comparison</p><h2>Prognostics strategy matrix</h2></div></div><div class="table-wrap"><table><thead><tr>${['Approach','RUL capability','Data requirement','Interpretability','Complexity','Maturity','Compute cost'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${matrix.map(row=>`<tr>${row.map((c,i)=>`<td><span class="${i?' '+badge(c):'method-name'}">${c}</span></td>`).join('')}</tr>`).join('')}</tbody></table></div></div><div class="card window-card"><p class="eyebrow">Maintenance recommendation</p><h2>Inspect within 28–46 days</h2><p>Prioritize hot-section inspection and vibration review before the forecast enters the high-risk band.</p><div class="timeline"><i></i><span class="today">Today</span><span class="window">Preferred window</span><span class="risk">Threshold</span></div><ul><li>Confirm vibration sensor calibration</li><li>Review thermal efficiency loss</li><li>Plan inspection before synthetic day 46</li></ul></div></section>
<section class="card change-card"><div class="change-copy"><p class="eyebrow">Sensitivity explorer</p><h2>What changes the recommendation?</h2><p>Adjust the three most influential evidence conditions. The result updates with the same deterministic method used on page one.</p><div class="change-result"><span style="background:${w.s[2]}"></span><div><small>Recommended strategy</small><strong>${w.s[0]} · ${w.score}/100</strong><p>${w.s[4]} because the evidence mix changes its weighted suitability.</p></div></div></div><div class="change-controls">${range('data','Data availability')}${range('physics','Physics-model availability')}${range('safety','Safety criticality')}<div class="runner-up"><span>Next-best alternative</span><strong>${r[1].s[0]} · ${r[1].score}</strong></div></div></section></main>`}
function footer(){return `<footer><strong>PrognosIQ</strong><p>Independent research prototype using synthetic industrial data. Results do not represent Siemens Energy assets, measurements, models or proprietary information.</p><span>Methodology demonstration only · No diagnostic use</span></footer>`}
function render(){root.innerHTML=`<div class="app">${header()}${state.page==='selector'?selector():casePage()}${footer()}</div>`;root.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;history.pushState({},'',state.page==='case'?'/case-study':'/');scrollTo(0,0);render()});root.querySelectorAll('input[type=range]').forEach(i=>i.oninput=()=>{state[i.dataset.key]=+i.value;render()});const a=document.getElementById('asset');if(a)a.onchange=()=>{state.asset=a.value;render()};const rul=document.getElementById('rul');if(rul)rul.onclick=()=>{state.rul=state.rul>50?20:100;render()}}
addEventListener('popstate',()=>{state.page=location.pathname.includes('case-study')?'case':'selector';render()});state.page=location.pathname.includes('case-study')?'case':'selector';render();
